
(********************
 *
 * Converts UDINT to DT
 *
*********************)
@EXTERNAL FUNCTION UDINT_TO_DT : DT
VAR_INPUT
	in : UDINT;
END_VAR
END_FUNCTION

(********************
 *
 * Converts DWORD to TOD
 *
*********************)
@EXTERNAL FUNCTION DWORD_TO_TOD : TOD
VAR_INPUT
	in : DWORD;
END_VAR
END_FUNCTION

(********************
 *
 * Converts DT to UDINT
 *
*********************)
@EXTERNAL FUNCTION DT_TO_UDINT : UDINT
VAR_INPUT
	in : DT;
END_VAR
END_FUNCTION

(********************
 *
 * Converts DWORD to DT
 *
*********************)
@EXTERNAL FUNCTION DWORD_TO_DT : DT
VAR_INPUT
	in : DWORD;
END_VAR
END_FUNCTION

(********************
 *
 * Converts TIME to INT
 *
*********************)
@EXTERNAL FUNCTION TIME_TO_INT : INT
VAR_INPUT
	in : TIME;
END_VAR
END_FUNCTION

(********************
 *
 * Converts TOD to DWORD
 *
*********************)
@EXTERNAL FUNCTION TOD_TO_DWORD : DWORD
VAR_INPUT
	in : TOD;
END_VAR
END_FUNCTION

(********************
 *
 * Converts DWORD to DATE
 *
*********************)
@EXTERNAL FUNCTION DWORD_TO_DATE : DATE
VAR_INPUT
	in : DWORD;
END_VAR
END_FUNCTION

(********************
 *
 * Converts DATE to UDINT
 *
*********************)
@EXTERNAL FUNCTION DATE_TO_UDINT : UDINT
VAR_INPUT
	in : DATE;
END_VAR
END_FUNCTION

(********************
 *
 * Converts UDINT to DATE
 *
*********************)
@EXTERNAL FUNCTION UDINT_TO_DATE : DATE
VAR_INPUT
	in : UDINT;
END_VAR
END_FUNCTION

(********************
 *
 * Converts DINT to TOD
 *
*********************)
@EXTERNAL FUNCTION DINT_TO_TOD : TOD
VAR_INPUT
	in : DINT;
END_VAR
END_FUNCTION

(********************
 *
 * Converts TOD to DINT
 *
*********************)
@EXTERNAL FUNCTION TOD_TO_DINT : DINT
VAR_INPUT
	in : TOD;
END_VAR
END_FUNCTION

(********************
 *
 * Converts DATE to DWORD
 *
*********************)
@EXTERNAL FUNCTION DATE_TO_DWORD : DWORD
VAR_INPUT
	in : DATE;
END_VAR
END_FUNCTION


(********************
 *
 * Converts TIME to DINT
 *
*********************)
@EXTERNAL FUNCTION TIME_TO_DINT : DINT
VAR_INPUT
	in : TIME;
END_VAR
END_FUNCTION

(********************
 *
 * Converts DT to DWORD
 *
*********************)
@EXTERNAL FUNCTION DT_TO_DWORD : DWORD
VAR_INPUT
	in : DT;
END_VAR
END_FUNCTION


(********************
 *
 * Converts TIME to DWORD
 *
*********************)
@EXTERNAL FUNCTION TIME_TO_DWORD : DWORD
VAR_INPUT
	in : TIME;
END_VAR
END_FUNCTION

(********************
 *
 * Converts TIME to REAL
 *
*********************)
@EXTERNAL FUNCTION TIME_TO_REAL : REAL
VAR_INPUT
	in : TIME;
END_VAR
END_FUNCTION